//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        [Required]
        [RegularExpression(@"^[a-zA-Z]{1,10}$", ErrorMessage = "Invalid first name (at most 10 chars)")]
        public string fname { get; set; }
        [DisplayName("Last Name")]
        [Required]
        [RegularExpression(@"^[a-zA-Z]{1,10}$", ErrorMessage = "Invalid last name (at most 10 chars)")]
        public string lname { get; set; }
        [DisplayName("Course")]
        [Required]
        public int course_id { get; set; }
        [DisplayName("Enrol Date")]
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime enrol_date { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
